[tox]
envlist =
    isort-check
    black-check
    flake8-check
    pylint-check
    py
    coverage_report
skip_missing_interpreters = true

[testenv]
deps =
    -r requirements.txt
    -r requirements-dev.txt
commands = pytest --cov=openweather --cov-report=term

[testenv:coverage_report]
deps =
    coverage
commands =
    coverage run -m pytest
    coverage report --fail-under=95 -m
    coverage html

[testenv:isort-check]
deps = isort
commands = isort --check-only --diff src/ tests/

[testenv:black-check]
deps = black
commands = black --check --diff src/ tests/

[testenv:flake8-check]
deps = flake8
commands = flake8 src/ tests/

[testenv:pylint-check]
deps =
    {[testenv]deps}
    pylint
commands = pylint src/openweather

[flake8]
max-line-length = 88
ignore = E203, E231, W503

[pylint.MESSAGES CONTROL]
disable = fixme, invalid-name, too-few-public-methods
